---
title: "assignement2_1"
author: "YANG Mengwei"
date: "10/8/2017"
output: html_document
---
##Exercice1

**Question 1a**

```{r echo=FALSE}
source("function.R")
print(sum_column(iris, "Sepal.Length"))
print(sum_column(iris, "Species"))
print(sum_column(warpbreaks, "breaks"))
```

**Question 1b**

```{r}
source("function.R")
print(my_sum(iris$Sepal.Length))
print(sum_column(iris, "Species"))
print(sum_column(warpbreaks, "breaks"))
```

**Question 1c**

```{r}
source("function.R")
print(sum_divided_by(iris$Sepal.Length, 12))
print(sum_divided_by(iris$Species, 22))
print(sum_divided_by(iris$Sepal.Length, "Not numeric"))
print(sum_divided_by(warpbreaks$breaks, -12))
```

**Question 1d**
```{r}
source("function.R")
print(my_mean(iris$Sepal.Length))
print(my_mean(iris$Species))
print(my_mean(warpbreaks$breaks))
```

##Exercice2

**Question 2a**

```{r}
# Return a violin plot.
##ARGUMENTS:
# d: a data frame or tibble
# var: the name of a column of d containing the dependent variable, provided as a
# string
# grouping_var: the name of a column of d containing a grouping variable,
# provided as a string
##RETURN VALUE:
# A ggplot plot object containing a violin plot, grouped by the values
# of the grouping variable.
#
grouped_violin_plot <- function(d, var, grouping_var) {
# Create the base ggplot object
p <- ggplot2::ggplot(d, ggplot2::aes_string(y=var,
x=grouping_var,
fill=grouping_var))+ ggplot2::geom_violin() 
# YOUR CODE HERE: Create a violin plot
return(p)
}

print(grouped_violin_plot(iris, "Sepal.Length", "Species"))
```

```{r}
grouped_violin_plot <- function(d, var, grouping_var) {
# Create the base ggplot object
p <- ggplot2::ggplot(d, ggplot2::aes_string(y=var,
x=grouping_var,
fill=grouping_var))+ ggplot2::geom_violin() }
p <- grouped_violin_plot(iris, "Sepal.Length", "Species")+ggplot2::scale_fill_brewer(palette ="PuBu")+ggplot2::labs(title="Iris Data")
print(p)

```